### ISSUE TITLE
about using JSON and templates

### ISSUE THREAD

**Issue by programacion-web** [grahamb/tab_overview_sample_zimlet#2]

**Comment by grahamb** [comment]
Hi there,

Sorry, I'm really not sure what you're asking. This repo is an example for a tab zimlet with a custom tree view. If you look at the code, you'll see how the view is being built from an object. How you build that object from whatever data source you're using is up to you.

Sorry I can't be more helpful; I haven't done any major zimlet development in years. As you can see, this repo is five years old; I don't know if it will work unmodified in a Zimbra 8 installation. We do still have a zimlet deployed in production that uses this technique (this example repo was based from that zimlet), so my guess is that it still works.
